Signed_Statement = #6.18(COSE_Sign1)

COSE_Sign1 = [
  protected   : bstr .cbor Protected_Header,
  unprotected : Unprotected_Header,
  payload     : bstr / nil,
  signature   : bstr
]

Protected_Header = {
  &(alg: 1) => int
  &(CWT_Claims: 15) => CWT_Claims
  &(crit: 2) => [+ "attestedsvc"]
  &(attestedsvc: "attestedsvc") => Attested_Service_Claims
  * label => any
}

Attested_Service_Claims = {
  &(attestation: "attestation") => bstr
  &(attestation_type: "attestation_type") => tstr
  &(snp_endorsements: "snp_endorsements") => bstr
  &(uvm_endorsements: "uvm_endorsements") => bstr
  &(svc_id: "svc_id") => tstr
  &(ver: "ver") => int
  &(cose_key: "cose_key") => COSE_EC_Key
  * label => any
}

COSE_EC_Key = {
  &(kty: 1) => int
  ? &(crv: -1) => int
  ? &(x: -2) => bstr
  ? &(y: -3) => bstr
  * label => any
}

CWT_Claims = {
  &(iss: 1) => tstr
  ? &(sub: 2) => tstr
  ? "svn" => int
  * label => any
}

Unprotected_Header = {
  * label => any
}

label = int / tstr