trigger: none

parameters: # parameters are shown up in ADO UI in a build queue time
- name: debug
  displayName: Enable debug output
  type: boolean
  default: false
- name: CCF_VERSION
  displayName: Target CCF version to build for
  type: string
  default: 6.0.0-dev3

variables:
  SCITT_CI: 1 # used in scitt builds and tests
  DEBIAN_FRONTEND: noninteractive # do not expect the user to provide answers to some commands
  SETUPTOOLS_USE_DISTUTILS: stdlib # python recommended fix for ubuntu 22.04
  # Docker image which is used to build and test "virtual" platform https://aka.ms/obpipelines/containers
  # SGX container setup through "LinuxContainerImage2" does not work in the custom pool of SGX VMs and the default ones do not support SGX
  LinuxContainerImage: 'ghcr.io/microsoft/ccf/app/dev/virtual:ccf-${{ parameters.CCF_VERSION }}' # implicit default but otherwise could be set like => target: 'linux_build_container'
  CDP_DEFINITION_BUILD_COUNT: $[counter('', 0)] # needed for onebranch.pipeline.version task https://aka.ms/obpipelines/versioning
  # CodeQL settings to target the remote repository instead of this wrapper one
  Codeql.Language: 'cpp,python,javascript'
  Codeql.ADO.Build.Repository.Provider: override # reference another repository
  Codeql.ADO.Build.Repository.Uri: https://github.com/microsoft/scitt-ccf-ledger # reference another repository

resources:
  repositories:
    - repository: templates
      type: git
      name: OneBranch.Pipelines/GovernedTemplates
      ref: refs/heads/main
    - repository: SCITT
      type: github
      endpoint: microsoft
      name: microsoft/scitt-ccf-ledger
      ref: $(Build.SourceBranch)

extends:
  template: v2/OneBranch.NonOfficial.CrossPlat.yml@templates # https://aka.ms/obpipelines/templates
  parameters:
    cloudvault: # https://aka.ms/obpipelines/cloudvault
      enabled: false
    globalSdl: # https://aka.ms/obpipelines/sdl
      perStage:
        sdl_sources:
          checkout_all_repos: true
      tsa:
       enabled: false
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)/.config/CredScanSuppressions.json
      policheck:
        break: true
      codeql: # https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/codeql/one-branch-codeql
        compiled:
          enabled: true
    stages:
    - stage: setup
      jobs:
      - job: setup
        pool:
          type: linux
        variables:
          ob_outputDirectory: '$(Build.SourcesDirectory)/out' # this directory is uploaded to pipeline artifacts, reddog and cloudvault. More info at https://aka.ms/obpipelines/artifacts
        steps:
        - task: onebranch.pipeline.version@1 # generates automatic version. For other versioning options check https://aka.ms/obpipelines/versioning
          displayName: Setup BuildNumber
          inputs:
            system: 'Patch'
            major: '1'
            minor: '0'
            name: scitt-ccf-ledger

    - stage: test_virtual_vm_build
      jobs:
      - job: format
        displayName: Code Formatting
        pool:
          type: linux
        variables:
          ob_outputDirectory: $(Build.SourcesDirectory)/out
        steps:
        - checkout: SCITT
          path: s/
          submodules: recursive
          lfs: false
        - template: .pipelines/ado_pipauth.yml@self
        - script: $(Build.SourcesDirectory)/scripts/ci-checks.sh
          displayName: "CI checks"

      - template: .pipelines/local_virtual_build.yml@self # https://learn.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops&pivots=templates-includes#use-other-repositories
        parameters:
          Name: clang_tidy
          DisplayName: Clang tidy
          RunTests: false
          Environment:
            CMAKE_BUILD_TYPE: Debug
            ENABLE_CLANG_TIDY: ON
          InstallPackages: [ libcurl4-openssl-dev, clang-tidy-10 ]

      - template: .pipelines/local_virtual_build.yml@self
        parameters:
          Name: test_virtual
          DisplayName: Build and test (Virtual)
          FunctionalTestArguments: '--enable-faketime'
          Environment:
            CMAKE_BUILD_TYPE: Debug
          InstallPackages: [ libcurl4-openssl-dev, faketime ]

    - stage: test_virtual_docker_build
      jobs:
      - job: test_virtual_docker
        pool:
          type: linux
          isCustom: true
          name: scitt-dc-pool
        variables:
          ob_outputDirectory: $(Build.SourcesDirectory)/out
          PLATFORM: virtual
          CXXFLAGS: -ferror-limit=0
          NINJA_FLAGS: -k 0
        steps:
          - checkout: SCITT
            path: s/
            submodules: recursive
            fetchTags: true
            fetchDepth: 0
            lfs: false
          - script: ./docker/build.sh
            displayName: Build virtual with Docker
          - template: .pipelines/python.yml@self
          - script: ./run_functional_tests.sh
            displayName: Run Functional Tests
            env:
              PLATFORM: virtual
              DOCKER: 1
              ELEVATE_PRIVILEGES: true

    - stage: test_sgx_vm_container_build
      jobs:

      ## About SGX support on OneBranch
      # Local sgx build is not possible without changing the vm image in the pool
      # from ubuntu 22 to ubuntu 20 because dcap was not released to v22 and is not
      # installable. This was because openenclave is scheduled for deprecation. 
      # Ubuntu 20 image with sgx support does not exist in the marketplace for us to switch to.
      # Alternatively, it was being executed through the container in azure pipelines but
      # when using custom pool image the usual container build support is not there so it 
      # need to be run manually through docker.

    - stage: snp_build
      jobs:
      - job: snp_build
        pool:
          type: linux
        variables:
          ob_outputDirectory: $(Build.SourcesDirectory)/out
          PLATFORM: snp
          CXXFLAGS: -ferror-limit=0
          NINJA_FLAGS: -k 0 
          LinuxContainerImage: 'ghcr.io/microsoft/ccf/app/dev/snp:ccf-${{ parameters.CCF_VERSION }}'
        steps:
          - checkout: SCITT
            path: s/
            submodules: recursive
            fetchTags: true
            fetchDepth: 0
            lfs: false
          - script: |
              sudo apt-get update
              sudo apt-get install -y libcurl4-openssl-dev
            displayName: Install additional packages
          - script: ./build.sh
            displayName: Build snp
            env:
              PLATFORM: snp
              BUILD_TESTS: OFF
    
    - stage: snp_docker_build
      jobs:
      - job: snp_docker_build
        pool:
          type: linux
          isCustom: true
          name: scitt-dc-pool
        variables:
          ob_outputDirectory: $(Build.SourcesDirectory)/out
          PLATFORM: snp
          CXXFLAGS: -ferror-limit=0
          NINJA_FLAGS: -k 0 
        steps:
          - checkout: SCITT
            path: s/
            submodules: recursive
            fetchTags: true
            fetchDepth: 0
            lfs: false
          - script: ./docker/build.sh
            displayName: Build snp with Docker
            env:
              PLATFORM: snp
